INSERT INTO topping (name) VALUES ('Veggies');
INSERT INTO topping (name) VALUES ('Roma Tomatoes');
INSERT INTO topping (name) VALUES ('Red Onions');
INSERT INTO topping (name) VALUES ('Spinach');
INSERT INTO topping (name) VALUES ('Broccoli');
INSERT INTO topping (name) VALUES ('Pineapple');
INSERT INTO topping (name) VALUES ('Jalapeno Peppers');
INSERT INTO topping (name) VALUES ('Kalamata Olives');
INSERT INTO topping (name) VALUES ('Fresh Mushrooms');
INSERT INTO topping (name) VALUES ('Meats');
INSERT INTO topping (name) VALUES ('Anchovies');
INSERT INTO topping (name) VALUES ('Bacon Crumble');
INSERT INTO topping (name) VALUES ('Bacon Strips');
INSERT INTO topping (name) VALUES ('Chicken');
INSERT INTO topping (name) VALUES ('Ground Beef');
INSERT INTO topping (name) VALUES ('Italian Ham');
INSERT INTO topping (name) VALUES ('Spicy Italian Sausage');
INSERT INTO topping (name) VALUES ('Steak Strips');
INSERT INTO topping (name) VALUES ('Cheese');
INSERT INTO topping (name) VALUES ('Feta Cheese');
INSERT INTO topping (name) VALUES ('Parmesan Cheese');
INSERT INTO topping (name) VALUES ('Provolone Cheese');
INSERT INTO topping (name) VALUES ('Extra Cheese');
INSERT INTO topping (name) VALUES ('Four Cheese Blend Topping');
INSERT INTO topping (name) VALUES ('Goat Cheese');
INSERT INTO topping (name) VALUES ('Mozzarella');

INSERT INTO base(name) VALUES ('Thin Crust');
INSERT INTO base(name) VALUES ('Flatbread Crust');
INSERT INTO base(name) VALUES ('Thick Crust');
INSERT INTO base(name) VALUES ('Focaccia');