DROP TABLE base IF EXISTS;
DROP TABLE pizza IF EXISTS;
DROP TABLE pizza_toppings IF EXISTS;
DROP TABLE topping IF EXISTS;

CREATE TABLE base (
  id   BIGINT generated BY DEFAULT AS IDENTITY,
  name VARCHAR(255),
  PRIMARY KEY (id)
);
CREATE TABLE pizza (
  id      BIGINT generated BY DEFAULT AS IDENTITY,
  name    VARCHAR(255),
  price   DECIMAL(19, 2),
  base_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE pizza_toppings (
  pizza_id    BIGINT NOT NULL,
  toppings_id BIGINT NOT NULL,
  PRIMARY KEY (pizza_id, toppings_id)
);
CREATE TABLE topping (
  id   BIGINT generated BY DEFAULT AS IDENTITY,
  name VARCHAR(255),
  PRIMARY KEY (id)
);

ALTER TABLE pizza
  ADD CONSTRAINT FKm6kai6c5evr38duyfh06ue29u FOREIGN KEY (base_id) REFERENCES base;
ALTER TABLE pizza_toppings
  ADD CONSTRAINT FK7tcti2cxau3csvbuwxn0scb93 FOREIGN KEY (toppings_id) REFERENCES topping;
ALTER TABLE pizza_toppings
  ADD CONSTRAINT FK78l5qtferc9qhfkkgyv99lmst FOREIGN KEY (pizza_id) REFERENCES pizza;